apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moneymanager-app
resources:
- namespace.yaml
- deployment.yaml
images:
- name: account
  newName: papawattu/moneymanager-account
  newTag: ed3157720e114edfe7c7c0b83096afdef9ada507
